version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: Grupo3
      POSTGRES_PASSWORD: gestiongrupo3
      POSTGRES_DB: BananaPlex
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    image: httpd:2.4
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"
